# ==== qBittorrent 客户端连接信息 ====
qbittorrent:
  host: "192.168.1.28"     # 客户端 IP 或域名
  port: 8005               # Web UI 端口
  username: "admin"        # 登录用户名
  password: "your_password_here"  # 登录密码

# ==== 删除种子时是否同时删除本地文件 ====
delete_files_on_remove: true

# ==== 需要统计数据的 tracker（用于 total 命令） ====
required_summer:
  - "tracker.m-your.cc"

# ==== 根据 tracker 域名限速（单位：KB/s） ====
upload_speed_limits_by_tracker:
  "pt.your": 600
  "ptl.your": 600
  
# 查询导出配置项
export_options:
# 是否对导出的种子进行去重 true或者false
  deduplicate: true  
  
# ==== 启用的检查策略列表（按顺序执行，串行过滤）====
# missing_trackers     tracker 列表，当种子没有该tracker时，会将该种子导出或删除 
# tracker_tag_filter   指定种子标签，当种子包含此标签，跳过
# official_group       指定官组后缀，当种子包含此后缀，跳过
active_strategies:
  - missing_trackers
  
# ==== 检查策略配置 ====
check_strategies:
  missing_trackers:
  # ==== tracker 列表，当种子没有该tracker时，会将该种子导出或删除 ====
    required_trackers:
      - tracker.xxx.com
  official_group:
    groups:
      group1: ["aaa","bbb"]
    selected_group: "group1"  # 指定当前使用的官组名称数组
  tracker_tag_filter:
    forbidden_tags:
      - "MOVIEPILOT"
      - "PTD"
      - "GAME"
